### ISSUE TITLE
[BUG]: Value cannot be null. (Parameter 'image')

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#12]
### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

Hello,

I'm trying to export a dashboard to PDF from the UI and I'm getting the following error in my backend:

    Value cannot be null. (Parameter 'image')

This full is the stack trace:

```
2023-03-31 18:47:23,117 INFO pool-4-thread-2 i.r.DefaultExportToolService - Downloading distribution sdk js file from: https://maven.revealbi.io/repository/public/com/infragistics/reveal/sdk/reveal-sdk-distribution/1.4.0/reveal-sdk-distribution-1.4.0-js.zip {}
2023-03-31 18:47:28,809 INFO pool-4-thread-2 i.r.DefaultExportToolService - Captured request: GET http://www.infragistics.com/css/quill.snow.css {}
2023-03-31 18:47:29,207 INFO pool-4-thread-2 i.r.DefaultExportToolService - Captured request: GET http://www.infragistics.com/jquery-3.4.1.min.js {}
2023-03-31 18:47:29,248 INFO pool-4-thread-2 i.r.DefaultExportToolService - Captured request: GET http://www.infragistics.com/dayjs.min.js {}
2023-03-31 18:47:29,264 INFO pool-4-thread-2 i.r.DefaultExportToolService - Captured request: GET http://www.infragistics.com/quill.js {}
2023-03-31 18:47:29,324 INFO pool-4-thread-2 i.r.DefaultExportToolService - Captured request: GET http://www.infragistics.com/Reveal/infragistics.reveal.js {}
2023-03-31 18:47:39,284 ERROR pool-4-thread-2 i.r.ExportTool - Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'image') {}
2023-03-31 18:47:39,285 ERROR pool-4-thread-2 i.r.ExportTool -   at Infragistics.Documents.Reports.Graphics.Image..ctor(Image image, Boolean enablePixelTransparency) {}
2023-03-31 18:47:39,285 ERROR pool-4-thread-2 i.r.ExportTool -   at Infragistics.PDFExportTool.CreateReportImage(Bitmap image) {}
2023-03-31 18:47:39,285 ERROR pool-4-thread-2 i.r.ExportTool -   at Infragistics.PDFExportTool.AddImagePage(Report report, Bitmap image, String title, String subtitle, PDFReportInfo info) {}
2023-03-31 18:47:39,285 ERROR pool-4-thread-2 i.r.ExportTool -   at Infragistics.PDFExportTool.AddCaptures(Report report, CPList captures, PDFReportInfo info) {}
2023-03-31 18:47:39,285 ERROR pool-4-thread-2 i.r.ExportTool -   at Infragistics.PDFExportTool.ExportDashboard(RPExportDashboardObject dashboardData, String outputPath) {}
2023-03-31 18:47:39,285 ERROR pool-4-thread-2 i.r.ExportTool -   at ExportTool.Program.Main(String[] args) {}
2023-03-31 18:47:39,285 ERROR pool-4-thread-2 i.r.DefaultDashboardExporter - Error when creating exported data {}
java.lang.Exception: Export failed with code 134. Check the logs for more details.
       at com.infragistics.reveal.engine.export.DefaultDashboardExporter$3.export(DefaultDashboardExporter.java:395)
       at com.infragistics.reveal.engine.export.DefaultDashboardExporter$3.onSuccess(DefaultDashboardExporter.java:312)
       at com.infragistics.reveal.engine.export.DefaultDashboardExporter.addProcessedWidget(DefaultDashboardExporter.java:546)
       at com.infragistics.reveal.engine.export.DefaultDashboardExporter.access$600(DefaultDashboardExporter.java:58)
       at com.infragistics.reveal.engine.export.DefaultDashboardExporter$5.handleResult(DefaultDashboardExporter.java:514)
       at com.infragistics.reveal.engine.export.DefaultDashboardExporter$5.handleResult(DefaultDashboardExporter.java:508)
       at com.infragistics.reveal.engine.RevealEngine$2.invoke(RevealEngine.java:161)
       at com.infragistics.reportplus.datalayer.VisualizationDataService.postProcessResult(VisualizationDataService.java:89)
       at com.infragistics.reportplus.datalayer.VisualizationDataService.access$500(VisualizationDataService.java:15)
       at com.infragistics.reportplus.datalayer.VisualizationDataService$1$1.invoke(VisualizationDataService.java:63)
       at com.infragistics.reportplus.datalayer.DataLayerService$3.invoke(DataLayerService.java:168)
       at com.infragistics.reportplus.datalayer.DataLayerService$6.invoke(DataLayerService.java:299)
       at com.infragistics.reportplus.datalayer.TabularDataService$3.invoke(TabularDataService.java:79)
       at com.infragistics.reportplus.datalayer.TabularDataService$6.invoke(TabularDataService.java:244)
       at com.infragistics.reportplus.datalayer.engine.adhoc.AdHocBuilder$1.invoke(AdHocBuilder.java:47)
       at com.infragistics.reportplus.datalayer.engine.adhoc.HierarchyDataBuilderBase$3$1.invoke(HierarchyDataBuilderBase.java:342)
       at com.infragistics.reportplus.datalayer.TabularDataService$8.invoke(TabularDataService.java:304)
       at com.infragistics.reportplus.datalayer.TabularDataService$24.invoke(TabularDataService.java:787)
       at com.infragistics.reportplus.datalayer.engine.db.NativeJdbcDbUtility.insertRecord(NativeJdbcDbUtility.java:305)
       at com.infragistics.reportplus.datalayer.engine.db.NativeJdbcDbUtility$4.invoke(NativeJdbcDbUtility.java:316)
       at com.infragistics.reportplus.datalayer.engine.db.NativeJdbcDbUtility$3.invoke(NativeJdbcDbUtility.java:231)
       at com.infragistics.reportplus.datalayer.engine.db.NativeJdbcDbUtility.getFieldValueFromSingleRecord(NativeJdbcDbUtility.java:102)
       at com.infragistics.reportplus.datalayer.engine.db.NativeJdbcDbUtility.existsRecord(NativeJdbcDbUtility.java:228)
       at com.infragistics.reportplus.datalayer.engine.db.NativeJdbcDbUtility.insertOrUpdateRecord(NativeJdbcDbUtility.java:310)
       at com.infragistics.reportplus.datalayer.engine.db.DbCacheStorage.storeData(DbCacheStorage.java:153)
       at com.infragistics.reportplus.datalayer.engine.TabularDataCacheService$3.invoke(TabularDataCacheService.java:118)
       at com.infragistics.reportplus.datalayer.engine.InMemoryCacheStorage.storeObject(InMemoryCacheStorage.java:77)
       at com.infragistics.reportplus.datalayer.engine.TabularDataCacheService.addData(TabularDataCacheService.java:108)
       at com.infragistics.reportplus.datalayer.TabularDataService.cacheData(TabularDataService.java:783)
       at com.infragistics.reportplus.datalayer.TabularDataService.cacheDataAndHandOff(TabularDataService.java:300)
       at com.infragistics.reportplus.datalayer.TabularDataService.access$300(TabularDataService.java:14)
       at com.infragistics.reportplus.datalayer.TabularDataService$5$2$2.invoke(TabularDataService.java:222)
       at com.infragistics.reportplus.datalayer.engine.InMemoryDataset.getTabularData(InMemoryDataset.java:110)
       at com.infragistics.reportplus.datalayer.TabularDataService$5$2.invoke(TabularDataService.java:217)
       at com.infragistics.reportplus.datalayer.TabularDataService$19.invoke(TabularDataService.java:641)
       at com.infragistics.reportplus.datalayer.engine.transformations.PivotTableTransformation$2$1.invoke(PivotTableTransformation.java:142)
       at com.infragistics.reportplus.datalayer.engine.pivot.PivotTableBuilder$1$1.invoke(PivotTableBuilder.java:292)
       at com.infragistics.reportplus.datalayer.engine.InMemoryDataset.copyToLoader(InMemoryDataset.java:171)
       at com.infragistics.reportplus.datalayer.engine.pivot.PivotTableBuilder$1.invoke(PivotTableBuilder.java:268)
       at com.infragistics.reportplus.datalayer.engine.TaskExecutionService$1.run(TaskExecutionService.java:47)
       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at java.base/java.lang.Thread.run(Thread.java:834)
```

I tracked this issue to /var/log/syslog where it mentions a core-dump coming from a tool called ExportTool:

```
process_exporter[2215]: 2023/03/31 19:09:23 error reading config file "/opt/process-exporter-0.7.10.linux-amd64/all.yml": error reading config file "/opt/process-exporter-0.7.10.linux-amd64/all.yml": open /opt/process-exporter-0.7.10.linux-amd64/all.yml: no such file or directory
systemd[1]: process_exporter_main.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: process_exporter_main.service: Failed with result 'exit-code'.
```

I can't provide more details in this public site, but on the support portal I put an image and a file.

**Comment by brianlagunas** [comment]
Have you reviewed the docs for setting up export on Java?

https://help.revealbi.io/web/configure-export#java

Is the issue happening even after everything is properly configured?
