### ISSUE TITLE
[BUG]: Custom Queries don't work with the Java SDK

### ISSUE THREAD

**Issue by mjsorensen** [RevealBi/Reveal.Sdk#132]
### SDK Version

1.6.1

### Client Framework

Angular

### Server Platform

Java

### Operating System

Mac

### Description

When I use the .setCustomQuery() option on the RVMySqlDataSourceItem, the server always throws the following exception when the code is executed:

2023-11-30 17:13:11.352  WARN 97777 --- [ool-1-thread-77] o.m.jdbc.message.server.ErrorPacket      : Error: 1046-3D000: No database selected
java.sql.SQLTransientConnectionException: (conn=453587) No database selected
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:302)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:840)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:779)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:698)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:641)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
	at org.mariadb.jdbc.Statement.executeQuery(Statement.java:125)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient.getResultSet(BaseJdbcClient.java:742)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient.runDataQueryInternal(BaseJdbcClient.java:232)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient.access$200(BaseJdbcClient.java:54)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient$6$1.invoke(BaseJdbcClient.java:200)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient$10.invoke(BaseJdbcClient.java:683)
	at com.infragistics.reveal.engine.SdkSecurityLayerService.getAuthenticationInfo(SdkSecurityLayerService.java:54)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient.createDataSourceConnection(BaseJdbcClient.java:674)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient.access$100(BaseJdbcClient.java:54)
	at com.infragistics.reportplus.datalayer.providers.sql.BaseJdbcClient$6.invoke(BaseJdbcClient.java:197)
	at com.infragistics.reportplus.datalayer.engine.TaskExecutionService$1.run(TaskExecutionService.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by gkaveckis** [comment]
Hi 
Thanks for reporting it. We crated an internal issue to track it AB#28251 
Regards

**Comment by brianlagunas** [comment]
It has been discovered that this is not technically a bug. Rather, for MySql you must fully qualify the table names with the data base in the `IRVDataSourceProvider`

For example:
```
//when using a MySqlDataSourceItem, you should use the fully qualified name for tables, otherwise it won't work
mySqlDataSourceItem.setCustomQuery(String.format("SELECT * FROM AdventureWorks.Sales_SalesOrderHeader WHERE SalesPersonID = %s", salesPersonId));
```

While not a bug, this is not the ideal dev experience. We will be updating this to not require the fully qualified table name.
