### ISSUE TITLE
[BUG]: Adding new visualization does not work by specific steps.

### ISSUE THREAD

**Issue by cleverdog** [RevealBi/Reveal.Sdk#211]
### SDK Version

1.6.6

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Operating System

Windows

### Description

Adding new visualization does not work with following steps:
1. Create a new dashboard.
2. Add a new visualization.
3. Select a data source as SQL.
4. Make a visualization.
5. Add a Text Box.
6. Save the dashboard.
7. Then, start editing the dashboard again.
8. Add a new visualization.

![fd49793aa6a4da8ef7a65f932c79fdcb](https://github.com/RevealBi/Reveal.Sdk/assets/5829221/8edf5262-9b63-4fae-9ccb-c4fe3efdb073)

### Error message
```
infragistics.reveal.js:163 Uncaught TypeError: Cannot read properties of null (reading 'dataSourceId')
    at Class.createDataSourcesWithDatabase (infragistics.reveal.js:163:1392489)
    at Class.getExistingDatasources (infragistics.reveal.js:163:1395794)
    at c.init (infragistics.reveal.js:163:1240329)
    at c.init (infragistics.reveal.js:177:112955)
    at new c (infragistics.reveal.js:65:695)
    at SdkDelegate.addWidgetTriggeredContinuation (infragistics.reveal.js:177:359552)
    at infragistics.reveal.js:177:358705
    at revealView.onDataSourcesRequested (RevealSdk.Client.html:73:13)
    at SdkDelegate.addWidgetTriggered (infragistics.reveal.js:177:358645)
    at c.addWidgetWithDatasourceId (infragistics.reveal.js:163:531872)
```
### Additional information
If I selected the excel file as data source, the problem can not be reproduced, I confirmed this issue with MS SQL and Postgres.

**Comment by TorreyBetts** [comment]
Hi @cleverdog (Motoki). Can you email or send me the project you used through Teams? I haven't reproduced the issue as of yet and I want to be sure I have the exact configuration you're using. Thanks!

**Comment by TorreyBetts** [comment]
Thanks @cleverdog, your issue was reproduced and notes were taken and added to our internal work item AB#31670.

**Comment by brianlagunas** [comment]
This have been fixed and will be available in our Aug release
