### ISSUE TITLE
[BUG]: nnot read properties of null (reading 'minimize')  

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#28]
### Company

N/A

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

I clicked by mistake this area pointed by the arrow while editing a visualization:

![image](https://user-images.githubusercontent.com/3975401/234901395-e9dd44b9-093c-455a-8f99-e63ca5b341c1.png)

And this exception was printed:

```caught exception TypeError: Cannot read properties of null (reading 'minimize')
    at c.minimizeWidget (infragistics.reveal-1.4.0.js:154:3672053)
    at c.widgetHeaderTitleClicked (infragistics.reveal-1.4.0.js:154:3672143)
    at c.dashboardTitleClicked (infragistics.reveal-1.4.0.js:154:3650589)
    at c.handleClick (infragistics.reveal-1.4.0.js:154:3648800)
    at c.beforeClick (infragistics.reveal-1.4.0.js:84:44941)
    at c.beforeClick (infragistics.reveal-1.4.0.js:84:279494)
    at c.checkIsOver (infragistics.reveal-1.4.0.js:84:41596)
    at c.callCheckIsOverForUp (infragistics.reveal-1.4.0.js:84:40705)
    at c.onMouseUp (infragistics.reveal-1.4.0.js:84:39944)
    at HTMLDivElement.<anonymous> (infragistics.reveal-1.4.0.js:84:31776)
    at HTMLDivElement.dispatch (jquery.min.js:2:43336)
    at y.handle (jquery.min.js:2:41320)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:23999:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23999:36)
```

After this exception happens, the Cancel and Save buttons on the visualization don't work anymore, nor the filter selection.

**Comment by brianlagunas** [comment]
This was recently fixed in AB#23120 and should be available in the release next week. If this still occurs in the upcoming 1.5 release, please comment on this issue and I will reopen.
