### ISSUE TITLE
[BUG]: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dwilches** [RevealBi/Reveal.Sdk#31]
### Company

N/A

### SDK Version

1.4.0

### Client Framework

Angular

### Server Platform

Java

### Description

While testing a new data source I got this error:

![image](https://user-images.githubusercontent.com/3975401/235526346-b345b1e8-43d9-4973-9271-cb69f4610847.png)

In my backend, the stack trace was:

```
2023-05-01 20:32:08,117 ERROR pool-4-thread-4 i.r.TaskExecutionUtility - ExecuteAsync failed for dataset:__JSON_JSON__ba582951-694a-43bb-bbe7-0cf2dcb37bb0___Url:https://my-server/api/console/actionPlan/?page=1&type=PLANNING_FF_au:https://my-server/api/console/actionPlan/?page=1&type=PLANNING_XDxoGRUOu7 when executing the unique operation. We'll be calling Finished to avoid, as much as possible, a lack of response to the client. However, this is an abnormal situation that should be investigated. {}

2023-05-01 20:32:08,124 INFO  pool-4-thread-6 i.r.DataLayerService - Error getting data from tabular service: Code OTHER: java.lang.NullPointerException
 java.lang.NullPointerException
        at com.infragistics.reportplus.datalayer.JsonUtility.containsKey(JsonUtility.java:332)
        at com.infragistics.reportplus.datalayer.JsonUtility.loadObject(JsonUtility.java:229)
        at com.infragistics.reportplus.datalayer.providers.json.TabularDataSourceConfig.getTableSchemaColumns(TabularDataSourceConfig.java:105)
        at com.infragistics.reportplus.datalayer.providers.json.JSONProvider.loadMetadata(JSONProvider.java:293)
        at com.infragistics.reportplus.datalayer.providers.json.JSONProvider.loadData(JSONProvider.java:219)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation$3$1.invoke(GetDataTransformation.java:154)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation.getCachedDataset(GetDataTransformation.java:104)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation.access$200(GetDataTransformation.java:13)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation$3.invoke(GetDataTransformation.java:143)
        at com.infragistics.reportplus.datalayer.engine.TaskExecutionUtility$1.invoke(TaskExecutionUtility.java:54)
        at com.infragistics.reportplus.datalayer.engine.TaskExecutionService$1.run(TaskExecutionService.java:47)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2023-05-01 20:32:08,125 INFO  pool-4-thread-6 i.r.DataLayerService - Error getting data for widget And more titles. Error: Code OTHER: java.lang.NullPointerException
 java.lang.NullPointerException
        at com.infragistics.reportplus.datalayer.JsonUtility.containsKey(JsonUtility.java:332)
        at com.infragistics.reportplus.datalayer.JsonUtility.loadObject(JsonUtility.java:229)
        at com.infragistics.reportplus.datalayer.providers.json.TabularDataSourceConfig.getTableSchemaColumns(TabularDataSourceConfig.java:105)
        at com.infragistics.reportplus.datalayer.providers.json.JSONProvider.loadMetadata(JSONProvider.java:293)
        at com.infragistics.reportplus.datalayer.providers.json.JSONProvider.loadData(JSONProvider.java:219)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation$3$1.invoke(GetDataTransformation.java:154)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation.getCachedDataset(GetDataTransformation.java:104)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation.access$200(GetDataTransformation.java:13)
        at com.infragistics.reportplus.datalayer.engine.transformations.GetDataTransformation$3.invoke(GetDataTransformation.java:143)
        at com.infragistics.reportplus.datalayer.engine.TaskExecutionUtility$1.invoke(TaskExecutionUtility.java:54)
        at com.infragistics.reportplus.datalayer.engine.TaskExecutionService$1.run(TaskExecutionService.java:47)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by brianlagunas** [comment]
An you provide more information about the data source you were trying to create? Which data source? We’re you resting it on the client or we’re you providing the connection info on the server? Was it a. Data source or data source item? Please provide as much detail as possible.

**Comment by dwilches** [comment]
This is the code I used to create the data source in my JavaScript code:
```javascript
getDataSourceX() {
    const rvDataSource: RevealApi.RVRESTDataSource = new $.ig.RVRESTDataSource();
    rvDataSource.id = "hello-world";
    rvDataSource.url = "https://my-server/api/console/actionPlan/?page=1&type=REDACTED";
    rvDataSource.title = "My title";
    rvDataSource.contentType = "application/json";
    rvDataSource.method = "GET";

    const dsItem = new $.ig.RVRESTDataSourceItem(rvDataSource);
    dsItem.id = "hello-world-item";
    dsItem.title = "Another title";

    const jsonDsItem = new $.ig.RVJsonDataSourceItem(dsItem);
    jsonDsItem.defaultRefreshRate = 0;
    jsonDsItem.title = "And more titles";
    return jsonDsItem;
}
```

And the data looked like this (redacted the data but kept the structure intact):
```
{
  "page": 1,
  "totalPages": 1,
  "totalCount": 1,
  "items": [
    {    
      "id": 9,
      "name": "REDACTED",
      "state": "REDACTED",
      "field1": null,
      "field2": null,
      "someDate": "2023-05-15",
      "someDateTime": "2023-05-15T17:25:15.255750Z",
      "field3": "",
      "field4": [
        {    
          "id": 12,
          "title": "REDACTED",
          "information": "REDACTED",
          "thingList": [
            {
              "mykey": "REDACTED",
              "summary": "REDACTED",
              "severity": "HIGH",
              "fieldX": 10
            },   
            {
              "mykey": "REDACTED",
              "summary": "REDACTED",
              "severity": "HIGH",
              "fieldX": 10
            },   
            ...
            {
              "mykey": "REDACTED",
              "summary": "REDACTED",
              "severity": "HIGH",
              "fieldX": 10
            }
          ],
          "field5": [],
          "field6": [
            {
              "field7": 6816,
              "hostname": "my-other-server",
              "ip": "REDACTED"
            }
          ]
        }
      ],
      "createdBy": "me",
      "lastAt": "2023-05-01T17:25:15.230765Z"
    }
  ]
}

```

**Comment by brianlagunas** [comment]
Using the rest data source item object requires defining a config that represents the json structure. This is a documentation issue we are aware of and we are also looking at ways to improve this experience.  

I assume the data source works just fine, it’s just the data source items?

**Comment by dwilches** [comment]
The data source loaded ok. I could even see the fields in the editor (it had a lot of `../` but at least showed me it was receiving my data). The exception happened when I dragged&dropped the fields to start to build a graph.

**Comment by brianlagunas** [comment]
Which fields did you drag and drop? We’re you dropping into values, rows, columns, categories, etc? Which chart type were you trying to create? You need to be very specific. We need as much detail as you can give us in order to debug the issue. 

Can you privately send us some sample data to test with or even a reproduction dashboard?

**Comment by TorreyBetts** [comment]
Based on what you said @dwilches my guess is that you're not updating the resourceItem on the RVJsonDataSourceItem instance that gets passed into dataSourceItemProvider.

```
if (dataSourceItem instanceof RVJsonDataSourceItem) {
    const jsonDSI = <RVJsonDataSourceItem>dataSourceItem;
    const restDS = <RVRESTDataSource>jsonDSI.resourceItem?.dataSource;
    restDS.id = "hello-world";
    restDS.url = "https://my-server/api/console/actionPlan/?page=1&type=REDACTED";
    restDS.title = "My title";
    restDS.contentType = "application/json";
    restDS.method = "GET";
}
```

Your code may differ, although I think based on the above, you may get the gist of it.

**Comment by dwilches** [comment]
@TorreyBetts I have a method `IRVDataSourceProvider.changeDataSourceItem` where I validate the host in the url, validate some other aspects of the url and do placeholder replacements (we have our own placeholders in the urls). It looks like this:

```java
@Override
public RVDataSourceItem changeDataSourceItem(final IRVUserContext userContext,
                                             final String dashboardId,
                                             final RVDataSourceItem dataSourceItem) {
    if (dataSourceItem instanceof RVRESTDataSourceItem) {
        final RVRESTDataSourceItem dsItem = (RVRESTDataSourceItem)dataSourceItem;
        // some validations here
        dsItem.setUrl(myReplace(dsItem.getUrl()));
    } else if (dataSourceItem instanceof RVJsonDataSourceItem) {
        final RVRESTDataSourceItem dsItem = (RVRESTDataSourceItem)((RVJsonDataSourceItem)dataSourceItem)
                .getResourceItem();
        // some other validations here
        dsItem.setUrl(myReplace(dsItem.getUrl()));
    } else {
        throw new RuntimeException("some error here");
    }
    return dataSourceItem;
}
```

In this case, the url used doesn't have any of our custom placeholders so `myReplace` returns the same value it receives.

> my guess is that you're not updating the ResourceItem on the RVJsonDataSourceItem instance that gets passed into changeDataSourceItem method

Should I be changing it? I'm only replacing the url in that method as per the code above. I'm not interested in changing anything like the HTTP method, datasource id, title nor content-type. But should I be changing something?

**Comment by TorreyBetts** [comment]
@dwilches From that added context it looks like the configuration on the client and server would do what it expected. Although, if you are able to debug, it may be good to check that the resource item contains the necessary values at that point. Another point of error could be the usage of defaultRefreshRate set to 0. There are cases internally where setting that to 0 results in an exception. If you could, try setting that to 1 for example. Should that work, we can write up a bug if one doesn't already exist. If we still have an issue I'll recreate a similar sample to figure out where it's failing so we can get the issue fixed.

**Comment by dwilches** [comment]
Setting this test again to debug or change `defaultRefreshRate` would take too long on my side (requires backend changes).

And as this issue is not happening with the other data sources we have because we are manipulating the data structure to flatten it and removing top-level objects, my current plan is to do the same data manipulation to avoid this issue.

Also from what Brian said, it seems I should set that json structure regardless:

> Using the rest data source item object requires defining a config that represents the json structure.
