### ISSUE TITLE
[BUG]: Creating widget based on SQL Stored Procedure Data Item throws exception when table is empty

### ISSUE THREAD

**Issue by agroton-libtax** [RevealBi/Reveal.Sdk#58]
### Company

Liberty Tax

### SDK Version

1.5.0

### Client Framework

Angular

### Server Platform

ASP.NET

### Description

I have a "Data Item" set up to call a sproc in an Azure SQL DB, so that I can pull info from IRVUserContext to pass into the ProcedureParameters.
![image](https://github.com/RevealBi/Reveal.Sdk/assets/136626707/1c52a7cc-aa54-4398-9539-d126e8156893)

When I try to create a new visualization with this data source item, it fails at /createwidget, and the following SDK exception is logged:
```
Reveal.Sdk: Information: Returning DataLayerError for method CreateWidget. Details: Code Other: Object reference not set to an instance of an object.
   at Infragistics.ReportPlus.DataLayer.Providers.MsSql.MsSqlClient.GetSchema(DataTable dbSchema)
   at Infragistics.ReportPlus.DataLayer.Providers.MsSql.MsSqlClient.<>cDisplayClass12_1.<RunDataQueryInternal>b2()
   at Infragistics.ReportPlus.DataLayer.Impersonation.RunImpersonated(String username, String domain, String password, ExecutionBlock block)
   at Infragistics.ReportPlus.DataLayer.ImpersonationService.RunImpersonated(IDataLayerUserContext userContext, AuthenticationCredentials credentials, ExecutionBlock block)
   at Infragistics.ReportPlus.DataLayer.Providers.MsSql.MsSqlClient.<>cDisplayClass12_0.<RunDataQueryInternal>b0()
```

If I select the parent database from "Data Stores" and select the sproc from there and supply hard-coded params, it runs and the widget is created successfully. This bug only occurs with a custom Data Source Item configured to run the sproc.

The table that the sproc selects from is currently empty as it is a brand new database and I was told this is the source of the exception.

Video demo:
https://github.com/RevealBi/Reveal.Sdk/assets/136626707/3cbff80a-6fed-42d1-8c62-efb500ea5912

**Comment by TorreyBetts** [comment]
This morning I emptied the test database table I created to investigate this initial issue. Upon testing with stored procedure parameters that match their defined data type, all is working as intended. Internally, our code that generates a query will inject a NULL value when the data type for a parameter doesn't match its definition. This in turn can cause unknown behavior.
