### ISSUE TITLE
[BUG]: Cannot add visualization when editing dashboard that contains text boxes and visualizations

### ISSUE THREAD

**Issue by brprigge** [RevealBi/Reveal.Sdk#73]
### Company

CP Hub LLC

### SDK Version

1.5.0

### Client Framework

HTML/JavaScript

### Server Platform

ASP.NET

### Description

Given that...
...I have an existing dashboard that contains BOTH text boxes and visualizations
...I have loaded that dashboard from the JSON string
When...
...I try to edit the dashboard and add a visualization
Then...
... (Current State) I receive an error in the console
... (Expected State) I am able to add a new visualization.

```
Uncaught TypeError: Cannot read properties of null (reading 'dataSourceId')
    at Class.createDataSourcesWithDatabase (infragistics.reveal.js:154:1349817)
    at Class.getExistingDatasources (infragistics.reveal.js:154:1353122)
    at c.init (infragistics.reveal.js:154:1197493)
    at c.init (infragistics.reveal.js:168:105232)
    at new c (infragistics.reveal.js:56:695)
    at SdkDelegate.addWidgetTriggeredContinuation (infragistics.reveal.js:168:324583)
    at infragistics.reveal.js:168:323736
    at VueComponent.datasourcesRequested (AdHocDashboard.vue:61:9)
    at SdkDelegate.addWidgetTriggered (infragistics.reveal.js:168:323676)
    at c.addWidgetWithDatasourceId (infragistics.reveal.js:154:494786)
```

**Comment by brianlagunas** [comment]
Logged with internal item AB#26484

**Comment by PVillarmarzo** [comment]
Hello @brprigge  , have you made any progress on this issue? If not, please don't forget to send us a small example in a standalone application recreating it.
